### ISSUE TITLE
Error during instantiation of `qsip_source_data` object

### ISSUE THREAD

**Issue by colinvwood** [jeffkimbrel/qSIP2#3]
When following the "Standard qSIP Workflow" tutorial, during the step that instantiates the `quip_source_data` object:

```R
source_object <- qsip_source_data(source_df,
  isotope = "Isotope",
  isotopolog = "isotopolog",
  source_mat_id = "source"
)
```

I get the following error:

```
Error in duplicated(self@data["source_mat_id"]) : 
  trying to get slot "data" from an object (class "qsip_source_data") that is not an S4 object 
```

R version: 4.2.2
qSIP2 version: 0.10.1

**Comment by colinvwood** [comment]
That didn't change anything, but after updating R (and thus reinstalling all dependencies) this was fixed. Not sure where things were going wrong. Thanks for the quick help!

**Comment by jeffkimbrel** [comment]
Great, glad it resolved itself. I've noticed some folks had issues when running older versions of R (4.0.x), but your specs seemed like they should work OK. Let me know if you run into other issues.
