### ISSUE TITLE
Typo in `qsip_data` object instantiation output

### ISSUE THREAD

**Issue by colinvwood** [jeffkimbrel/qSIP2#6]
When instantiating a `qsip_data` object I got the following output:

```
There are 2 source_mat_ids, and they are all shared between the source and sample objects
WARNING: feature_data has 12 feature_id(s) that are missing from the sample_data
(...)
```

Shouldn't the second line read:

WARNING: feature_data has 12 **sample_id(s)** that are missing from the sample_data

instead?

**Comment by jeffkimbrel** [comment]
Good catch, thanks. I've made some updates to the `find_share_ids()` and `show_unshared_ids()` functions to fix this typo, as well as make the naming and documentation more consistent.
